algemene_voorwaarden.html: algemene_voorwaarden.adoc
	asciidoctor algemene_voorwaarden.adoc

algemene_voorwaarden.pdf: algemene_voorwaarden.adoc
	asciidoctor-pdf -o algemene_voorwaarden.pdf -a pdf-theme=jandot-theme.yml algemene_voorwaarden.adoc
