algemene_voorwaarden.html: algemene_voorwaarden.adoc
	asciidoctor algemene_voorwaarden.adoc

algemene_voorwaarden.pdf: algemene_voorwaarden.adoc
	asciidoctor-pdf -o algemene_voorwaarden.pdf -a pdf-theme=jandot-theme.yml algemene_voorwaarden.adoc

terms_and_conditions.html: terms_and_conditions.adoc
	asciidoctor terms_and_conditions.adoc

terms_and_conditions.pdf: terms_and_conditions.adoc
	asciidoctor-pdf -o terms_and_conditions.pdf -a pdf-theme=jandot-theme.yml terms_and_conditions.adoc
